export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
export const GET_CHARACTER_DETAILS = 'GET_CHARACTER_DETAILS'
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS'
export const GET_LOCATION_DETAILS = 'GET_LOCATION_DETAILS'
export const GET_ALL_EPISODES = 'GET_ALL_EPISODES'
export const GET_EPISODE_DETAILS = 'GET_EPISODE_DETAILS'

export const FETCH_TODOS_STARTED = 'FETCH_TODOS_STARTED'
export const FETCH_TODOS_SUCCEEDED = 'FETCH_TODOS_SUCCEEDED'
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED'

export const CLEAR_STATES = "CLEAR_STATES"